### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by umutuluer** [tbrand/roulette#1]
Hi!
My crystal version is 0.25.1
LLVM is 5.0.2
OSX is 10.14 Mojave
![image](https://user-images.githubusercontent.com/2777920/48049487-e60df180-e1af-11e8-886d-5a958b7ed431.png)

**Comment by tbrand** [comment]
Hi @umutuluer, thanks for the trying!
You know crystal is still under the development. So they drop compatibility frequently.
Could you try it on the latest version? (0.27.0)

I did compile it on [0.26.0](https://github.com/tbrand/roulette/blob/master/shard.yml#L17) but hopefully  be built on the latest.

**Comment by umutuluer** [comment]
Hi @tbrand i was completed upgrading, yes you are right, it works. 

Thanks

**Comment by tbrand** [comment]
Cool :+1:
